from __future__ import annotations

import re
import unicodedata

PHRASE_REPLACEMENTS = {
    "al vapor": "steamed",
    "al horno": "baked",
    "al oven": "baked",
    "al estilo": "style",
    "aceite de oliva virgen extra": "extra-virgin olive oil",
    "aceite de sesamo tostado": "toasted sesame oil",
    "aceite de sesamo": "sesame oil",
    "aceite de girasol": "sunflower oil",
    "aceite neutro": "neutral oil",
    "agua de coccion de la pasta": "pasta cooking water",
    "agua de hidratacion": "soaking water",
    "agua fria": "cold water",
    "ajo negro": "black garlic",
    "almidon de maiz": "cornstarch",
    "almidon de patata": "potato starch",
    "arroz basmati": "basmati rice",
    "arroz blanco": "white rice",
    "arroz frito": "fried rice",
    "arroz jazmin": "jasmine rice",
    "arroz japones": "Japanese rice",
    "atun en lata": "canned tuna",
    "atun enlatado": "canned tuna",
    "azucar blanco": "white sugar",
    "azucar glas": "powdered sugar",
    "azucar moreno": "brown sugar",
    "azucar de palma": "palm sugar",
    "fryer of air": "air fryer",
    "bicarbonato sodico": "baking soda",
    "caldo de pollo": "chicken stock",
    "caldo de verduras": "vegetable stock",
    "carne picada": "ground meat",
    "chile de arbol": "arbol chile",
    "chiles de arbol": "arbol chiles",
    "chocolate negro": "dark chocolate",
    "contramuslos de pollo": "chicken thighs",
    "crema agria": "sour cream",
    "diente de ajo": "garlic clove",
    "dientes de ajo": "garlic cloves",
    "espinacas frescas": "fresh spinach",
    "harina de fuerza": "strong bread flour",
    "harina de maiz": "corn flour",
    "harina de trigo": "wheat flour",
    "huevo tamano l": "large egg",
    "huevos tamano l": "large eggs",
    "a la mantequilla": "with butter",
    "judias blancas": "white beans",
    "judias negras": "black beans",
    "judias verdes": "green beans",
    "leche entera": "whole milk",
    "levadura fresca": "fresh yeast",
    "levadura instantanea": "instant yeast",
    "levadura quimica": "baking powder",
    "liquido de coccion": "cooking liquid",
    "lomo de salmon": "salmon fillet",
    "mantequilla sin sal": "unsalted butter",
    "masa madre": "sourdough starter",
    "nata para cocinar": "cooking cream",
    "pan de leche japones": "Japanese milk bread",
    "pasta fresca": "fresh pasta",
    "pasta con cherrys": "pasta with cherry tomatoes",
    "pechuga de pollo": "chicken breast",
    "pechugas de pollo": "chicken breasts",
    "pimenton dulce": "sweet paprika",
    "pimenton picante": "hot paprika",
    "pimienta negra": "black pepper",
    "pollo al limon": "lemon chicken",
    "pollo asado": "roast chicken",
    "pollo frito": "fried chicken",
    "queso rallado": "grated cheese",
    "salsa de cacahuete": "peanut sauce",
    "salsa de chiles": "chile sauce",
    "salsa de soja": "soy sauce",
    "salsa teriyaki": "teriyaki sauce",
    "semillas de sesamo": "sesame seeds",
    "tomate triturado": "crushed tomato",
    "zumo de limon": "lemon juice",
}

POST_TEXT_REPLACEMENTS = {
    "cast iron bread": "cast iron pan",
    "heavy bread": "heavy pan",
    "sheet bread": "sheet pan",
    "the bread and": "the pan and",
    "tilt the bread": "tilt the pan",
    "dry bread": "dry pan",
    "bread over medium": "pan over medium",
    "bread over high": "pan over high",
    "bread over low": "pan over low",
    "bread or microwave": "pan or microwave",
    "in a bread": "in a pan",
    "bread-crisp": "pan-crisp",
}

WORD_REPLACEMENTS = {
    "aceite": "oil",
    "aceitunas": "olives",
    "aire": "air",
    "acelga": "chard",
    "acelgas": "chard",
    "acompanar": "serve with",
    "agridulce": "sweet and sour",
    "agua": "water",
    "aguacate": "avocado",
    "aguja": "pork neck",
    "aji": "chile",
    "ajo": "garlic",
    "ajos": "garlic",
    "albahaca": "basil",
    "albondigas": "meatballs",
    "almendras": "almonds",
    "albaricoques": "apricots",
    "alitas": "wings",
    "alcachofas": "artichokes",
    "alubias": "beans",
    "arbol": "arbol",
    "arroz": "rice",
    "asado": "roasted",
    "atun": "tuna",
    "autentica": "authentic",
    "autentico": "authentic",
    "azafran": "saffron",
    "azucar": "sugar",
    "baja": "low",
    "bambu": "bamboo",
    "berenjena": "eggplant",
    "berenjenas": "eggplants",
    "blancas": "white",
    "blanco": "white",
    "bolonesa": "bolognese",
    "bruselas": "Brussels",
    "brocoli": "broccoli",
    "cacahuete": "peanut",
    "calabacin": "zucchini",
    "calabaza": "pumpkin",
    "caldo": "stock",
    "caliente": "hot",
    "camarones": "shrimp",
    "carne": "beef",
    "casera": "homemade",
    "casero": "homemade",
    "caseros": "homemade",
    "castanas": "chestnuts",
    "cebolla": "onion",
    "cerdo": "pork",
    "champinones": "mushrooms",
    "chiles": "chiles",
    "chocolate": "chocolate",
    "coccion": "cooking",
    "cocido": "cooked",
    "cocidos": "cooked",
    "con": "with",
    "conejo": "rabbit",
    "costillas": "ribs",
    "coreana": "Korean",
    "coreanas": "Korean",
    "coreano": "Korean",
    "crujiente": "crispy",
    "cuartos": "quarters",
    "caseras": "homemade",
    "completa": "complete",
    "completo": "complete",
    "datiles": "dates",
    "de": "of",
    "del": "of",
    "dulce": "sweet",
    "el": "the",
    "deshidratados": "dehydrated",
    "empanada": "pie",
    "en": "in",
    "encurtidos": "pickled",
    "ensalada": "salad",
    "estilo": "style",
    "escoceses": "Scotch",
    "esparragos": "asparagus",
    "espanol": "Spanish",
    "espanola": "Spanish",
    "espinacas": "spinach",
    "fina": "fine",
    "frito": "fried",
    "fritos": "fried",
    "fritas": "fried",
    "frio": "cold",
    "fresca": "fresh",
    "fresco": "fresh",
    "frescos": "fresh",
    "fresa": "strawberry",
    "freidora": "fryer",
    "gambas": "prawns",
    "griega": "Greek",
    "griego": "Greek",
    "guisantes": "peas",
    "guiso": "stew",
    "hamburguesa": "burger",
    "hamburguesas": "burgers",
    "harina": "flour",
    "horno": "oven",
    "huevo": "egg",
    "huevos": "eggs",
    "iberico": "iberian",
    "jamon": "ham",
    "japones": "Japanese",
    "japonesa": "Japanese",
    "jazmin": "jasmine",
    "judias": "beans",
    "jugo": "juice",
    "leche": "milk",
    "lengua": "tongue",
    "lima": "lime",
    "limon": "lemon",
    "limena": "Lima-style",
    "lomo": "loin",
    "maiz": "corn",
    "machacadas": "smashed",
    "mas": "more",
    "mantequilla": "butter",
    "marroqui": "Moroccan",
    "mayonesa": "mayonnaise",
    "mermelada": "jam",
    "mexicana": "Mexican",
    "mexicano": "Mexican",
    "mejillones": "mussels",
    "meloso": "creamy",
    "miel": "honey",
    "modernizada": "modernized",
    "morada": "red",
    "moruno": "Moorish",
    "morunos": "Moorish",
    "mostaza": "mustard",
    "negro": "black",
    "negra": "black",
    "naranja": "orange",
    "navidena": "holiday",
    "napolitana": "Neapolitan",
    "nectarinas": "nectarines",
    "o": "or",
    "ostras": "oyster",
    "pan": "bread",
    "panecillos": "buns",
    "panceta": "pork belly",
    "para": "for",
    "parmesano": "parmesan",
    "patata": "potato",
    "patatas": "potatoes",
    "pera": "pear",
    "pepino": "cucumber",
    "pepinillos": "pickles",
    "pescado": "fish",
    "picada": "ground",
    "picado": "ground",
    "picante": "spicy",
    "picantes": "spicy",
    "perfectas": "perfect",
    "pina": "pineapple",
    "pollo": "chicken",
    "puerro": "leek",
    "pure": "puree",
    "queso": "cheese",
    "rabo": "oxtail",
    "ragu": "ragout",
    "rallado": "grated",
    "relleno": "stuffed",
    "rellenos": "stuffed",
    "repollo": "cabbage",
    "res": "beef",
    "rojo": "red",
    "rojos": "red",
    "romero": "rosemary",
    "salmon": "salmon",
    "salsa": "sauce",
    "salteadas": "sauteed",
    "samosas": "samosas",
    "sarten": "pan",
    "seco": "dried",
    "secos": "dried",
    "semillas": "seeds",
    "sesamo": "sesame",
    "sencillo": "simple",
    "setas": "mushrooms",
    "sopa": "soup",
    "solomillo": "beef tenderloin",
    "tailandes": "Thai",
    "tailandesa": "Thai",
    "tailandeses": "Thai",
    "tamano": "size",
    "temperatura": "temperature",
    "ternera": "beef",
    "tradicional": "traditional",
    "tomate": "tomato",
    "tomates": "tomatoes",
    "trigueros": "wild",
    "traseros": "hindquarters",
    "triturados": "crushed",
    "vaca": "beef",
    "vapor": "steamed",
    "turron": "nougat",
    "vacuno": "beef",
    "verde": "green",
    "verdes": "green",
    "verduras": "vegetables",
    "vinagre": "vinegar",
    "vinagrillos": "pickles",
    "y": "and",
    "yema": "yolk",
    "yogur": "yogurt",
    "zanahoria": "carrot",
    "zumo": "juice",
}

PROCEDURE_WORD_REPLACEMENTS = {
    **WORD_REPLACEMENTS,
    "pan": "pan",
    "abre": "open",
    "abrir": "open",
    "anade": "add",
    "anadelos": "add them",
    "anadiendo": "adding",
    "anadir": "add",
    "apaga": "turn off",
    "baja": "lower",
    "bate": "whisk",
    "batir": "whisk",
    "coccion": "cooking",
    "cocina": "cook",
    "cocinado": "cooked",
    "cocinados": "cooked",
    "cocinalos": "cook them",
    "cocinarlas": "cook them",
    "cocinarse": "be cooked",
    "cocinar": "cook",
    "cocer": "cook",
    "corta": "cut",
    "cortadas": "cut",
    "cortar": "cut",
    "cortalo": "cut it",
    "cortalos": "cut them",
    "cubre": "cover",
    "cubrir": "cover",
    "cuece": "cook",
    "deja": "let",
    "dejalo": "let it",
    "dejalas": "let them",
    "dejalos": "let them",
    "dejar": "let",
    "desala": "desalt",
    "desecha": "discard",
    "deshuesa": "debone",
    "disuelve": "dissolve",
    "divide": "divide",
    "dora": "brown",
    "dorar": "brown",
    "emulsiona": "emulsify",
    "enfria": "cool",
    "enfriar": "cool",
    "enjuaga": "rinse",
    "escurre": "drain",
    "extiende": "spread",
    "fermenta": "ferment",
    "frie": "fry",
    "hierve": "boil",
    "hervir": "boil",
    "hirviendo": "boiling",
    "hidrata": "hydrate",
    "hornea": "bake",
    "hornear": "bake",
    "incorpora": "add",
    "lava": "wash",
    "limpia": "clean",
    "mantener": "keep",
    "manten": "keep",
    "marina": "marinate",
    "masajea": "massage",
    "mezcla": "mix",
    "mezclalo": "mix it",
    "mezclando": "mixing",
    "mezclar": "mix",
    "muele": "grind",
    "moler": "grind",
    "pasa": "pass",
    "pela": "peel",
    "pelar": "peel",
    "pelarlas": "peel them",
    "pica": "chop",
    "picados": "chopped",
    "picar": "chop",
    "precalienta": "preheat",
    "prepara": "prepare",
    "preparar": "prepare",
    "procesa": "process",
    "ralla": "grate",
    "retira": "remove",
    "retirar": "remove",
    "reserva": "reserve",
    "reservar": "reserve",
    "reservada": "reserved",
    "reservado": "reserved",
    "reservalo": "reserve it",
    "reservalos": "reserve them",
    "saltea": "saute",
    "sazona": "season",
    "sazonar": "season",
    "separa": "separate",
    "sirve": "serve",
    "servir": "serve",
    "sofrie": "saute",
    "tapa": "cover",
    "templado": "warm",
    "tuesta": "toast",
    "tritura": "blend",
    "vaporera": "steamer",
    "vuelve": "return",
    "el": "the",
    "la": "the",
    "los": "the",
    "las": "the",
    "un": "a",
    "una": "a",
    "al": "to the",
    "hasta": "until",
    "durante": "for",
    "minutos": "minutes",
    "momento": "moment",
    "hora": "hour",
    "horas": "hours",
    "noche": "night",
    "nevera": "fridge",
    "reposar": "rest",
    "reposo": "rest",
    "remojo": "soak",
    "racion": "serving",
    "fuego": "heat",
    "medio": "medium",
    "bajo": "low",
    "alto": "high",
    "trozos": "pieces",
    "tiras": "strips",
    "textura": "texture",
    "todo": "everything",
    "toda": "all",
    "finas": "thin",
    "fino": "fine",
    "clara": "clear",
    "claras": "whites",
    "raciones": "servings",
    "ajustar": "adjust",
    "arce": "maple",
    "bien": "well",
    "blanca": "white",
    "bolsa": "bag",
    "bandeja": "tray",
    "bote": "jar",
    "cacerola": "pot",
    "cada": "each",
    "canela": "cinnamon",
    "cardamomo": "cardamom",
    "cebolleta": "scallion",
    "clavo": "clove",
    "coloca": "place",
    "congeladas": "frozen",
    "congelarlos": "freeze them",
    "cuela": "strain",
    "cuencos": "bowls",
    "cubierto": "coated",
    "dejarlo": "let it",
    "debajo": "underneath",
    "desmenuzarlas": "crumble them",
    "ebullicion": "boil",
    "falta": "needed",
    "fria": "cold",
    "funda": "melts",
    "gamba": "prawn",
    "gelifique": "gel",
    "glaseado": "glazed",
    "gotas": "drops",
    "grande": "large",
    "grano": "grain",
    "grasa": "fat",
    "impurezas": "impurities",
    "jengibre": "ginger",
    "junto": "together with",
    "laurel": "bay leaf",
    "lateral": "side",
    "ligeramente": "lightly",
    "limpio": "clean",
    "listos": "ready",
    "luego": "then",
    "maicena": "cornstarch",
    "marinado": "marinade",
    "mejor": "best",
    "misma": "same",
    "monosodico": "monosodium",
    "muy": "very",
    "nuevo": "again",
    "obtener": "get",
    "papel": "paper",
    "pasar": "transfer",
    "pequenos": "small",
    "peso": "weight",
    "piezas": "pieces",
    "pimienta": "pepper",
    "plato": "plate",
    "pochado": "poached",
    "polvo": "powder",
    "poner": "put",
    "pon": "put",
    "por": "per",
    "presiona": "press",
    "puedes": "you can",
    "profundamente": "deeply",
    "que": "that",
    "quede": "is",
    "ralladura": "zest",
    "reduce": "reduce",
    "refrigera": "refrigerate",
    "rejilla": "rack",
    "reposa": "rests",
    "retirando": "removing",
    "sal": "salt",
    "si": "if",
    "semillas": "seeds",
    "sirope": "syrup",
    "sobre": "on",
    "sumerge": "submerge",
    "sube": "raise",
    "tandas": "batches",
    "tiene": "has",
    "trocito": "small piece",
    "unas": "some",
    "unos": "about",
    "vegetal": "parchment",
    "vez": "time",
    "vino": "wine",
    "ya": "already",
    "montados": "assembled",
    "encima": "on top",
    "este": "this",
    "recien": "freshly",
}

SMALL_TITLE_WORDS = {"and", "or", "of", "the", "with", "for", "a", "an", "to", "in"}
ACRONYMS = {"bbq", "blt", "msg"}
SPANISH_SIGNAL_WORDS = {word for word in WORD_REPLACEMENTS if word not in {"and", "or", "of", "the", "with", "for"}}


def normalize_ascii(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    return "".join(char for char in normalized if not unicodedata.combining(char))


def _replace_phrase(text: str, source: str, target: str) -> str:
    return re.sub(rf"(?<!\w){re.escape(source)}(?!\w)", target, text)


def translate_name(value: str, *, title: bool = True) -> str:
    normalized_original = normalize_ascii(value)
    signal_text = re.sub(r"[/_()\-]+", " ", normalized_original).lower()
    signal_words = set(re.findall(r"[a-z0-9]+", signal_text))
    if normalized_original == value and not (
        any(source in signal_text for source in PHRASE_REPLACEMENTS) or bool(signal_words & SPANISH_SIGNAL_WORDS)
    ):
        return value

    text = normalized_original.replace("ñ", "n").replace("Ñ", "N").lower()
    text = re.sub(r"[/_]+", " / ", text)
    text = re.sub(r"[-]+", " ", text)
    text = re.sub(r"[(),;:]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    for source, target in sorted(PHRASE_REPLACEMENTS.items(), key=lambda item: len(item[0]), reverse=True):
        text = _replace_phrase(text, source, target)
    words = [WORD_REPLACEMENTS.get(word, word) for word in text.split()]
    text = re.sub(r"\s+", " ", " ".join(words)).strip()
    text = text.replace(" with with ", " with ")
    if not title:
        return text
    titled = []
    for idx, word in enumerate(text.split()):
        cleaned = word.strip(",")
        if cleaned in ACRONYMS:
            new_word = word.upper()
        elif idx > 0 and cleaned in SMALL_TITLE_WORDS:
            new_word = word
        else:
            new_word = word[:1].upper() + word[1:]
        titled.append(new_word)
    return " ".join(titled)


def translate_text(value: str) -> str:
    text = normalize_ascii(value)
    for source, target in sorted(PHRASE_REPLACEMENTS.items(), key=lambda item: len(item[0]), reverse=True):
        text = re.sub(rf"(?<!\w){re.escape(source)}(?!\w)", target, text, flags=re.IGNORECASE)
    for source, target in sorted(PROCEDURE_WORD_REPLACEMENTS.items(), key=lambda item: len(item[0]), reverse=True):
        text = re.sub(rf"(?<!\w){re.escape(source)}(?!\w)", target, text, flags=re.IGNORECASE)
    for source, target in sorted(POST_TEXT_REPLACEMENTS.items(), key=lambda item: len(item[0]), reverse=True):
        text = re.sub(rf"(?<!\w){re.escape(source)}(?!\w)", target, text, flags=re.IGNORECASE)
    return re.sub(r"\s+", " ", text).strip()
